name: Poll for Benchmarks on open PRs

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  publish_benchmark:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: publish benchmark
        uses: getgauge-contrib/artifact_as_comment@master
        with:
          workflow_file_name: ".github/workflows/tests.yml"
          artifact_name: "benchmark"
          file_name: "results.md"
