name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: read

jobs:
  benchmark:
    name: Benchmark ${{ matrix.project }} | PARALLEL= ${{ matrix.parallel }}
    runs-on: ubuntu-latest
    needs: [ functional-tests, lsp-tests ]
    strategy:
      matrix:
        project: [java_simple, java_maven, java_gradle]
        parallel: ['parallel', 'serial', 'multithreaded']
    env:
      BENCHMARK_OUT_DIR: "../out"

    steps:
      - uses: actions/checkout@v3
        with:
          path: gauge
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'gauge/go.mod'
          cache-dependency-path: 'gauge/go.sum'
        id: go

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Gauge
        run: |
          cd gauge
          go run build/make.go && go run build/make.go --install --prefix=/tmp/gauge --verbose
          echo "/tmp/gauge/bin" >> $GITHUB_PATH

      - name: Install gauge-java
        run: gauge install java

      - name: Prep benchmark
        uses: actions/checkout@v3
        with:
          repository: getgauge/gauge-benchmarks
          path: gauge-benchmarks
          ref: master

      - name: Run benchmark ${{matrix.project}} | ${{matrix.parallel}}
        id: benchmark_run
        env:
          PARALLEL: ${{ matrix.parallel != 'serial' }}
          enable_multithreading: ${{ matrix.parallel == 'multithreaded' }}
        run: |
          mkdir -p gauge-benchmarks/out
          cd gauge-benchmarks/${{ matrix.project }}
          ./run.sh

      - name: Upload benchmark
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.project}}_${{matrix.parallel}}
          path: gauge-benchmarks/out

  post_result_as_artifact:
    name: Aggregate and upload benchmark result as artifact.
    runs-on: ubuntu-latest
    needs: benchmark
    if: github.event_name == 'pull_request'

    steps:
      - name: Prep benchmark
        uses: actions/checkout@v3
        with:
          repository: getgauge/gauge-benchmarks
          path: gauge-benchmarks
          ref: master
      - name: Download benchmark results
        uses: actions/download-artifact@v3
        with:
          path: gauge-benchmarks/out/
      - name: Generate Comment String
        id: gen_comment_str
        run: |
          cd gauge-benchmarks
          ./generate_summary.sh > out/results.md
      - name: Publish Benchmark Result
        uses: actions/upload-artifact@v3
        with:
          name: benchmark
          path: gauge-benchmarks/out/results.md
